<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Neighborhood;

class NeighborhoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $neighborhoods = array(

            ['commune_id' => 1, 'name' => 'Otro'],
            ['commune_id' => 2, 'name' => 'Otro'],
            ['commune_id' => 3, 'name' => 'Otro'],
            ['commune_id' => 4, 'name' => 'Otro'],
            ['commune_id' => 5, 'name' => 'Otro'],
            ['commune_id' => 6, 'name' => 'Otro'],
            ['commune_id' => 7, 'name' => 'Otro'],
            ['commune_id' => 8, 'name' => 'Otro'],
            ['commune_id' => 9, 'name' => 'Otro'],
            ['commune_id' => 10, 'name' => 'Otro'],
            ['commune_id' => 11, 'name' => 'Otro'],
            ['commune_id' => 12, 'name' => 'Otro'],
            ['commune_id' => 13, 'name' => 'Otro'],
            ['commune_id' => 14, 'name' => 'Otro'],
            ['commune_id' => 15, 'name' => 'Otro'],
            ['commune_id' => 16, 'name' => 'Otro'],
            ['commune_id' => 17, 'name' => 'Otro'],
            ['commune_id' => 18, 'name' => 'Otro'],
            ['commune_id' => 19, 'name' => 'Otro'],
            ['commune_id' => 20, 'name' => 'Otro'],
            ['commune_id' => 21, 'name' => 'Otro'],
            ['commune_id' => 22, 'name' => 'Otro'],
            ['commune_id' => 23, 'name' => 'Otro'],
            ['commune_id' => 24, 'name' => 'Otro'],
            ['commune_id' => 25, 'name' => 'Otro'],
            ['commune_id' => 26, 'name' => 'Otro'],
            ['commune_id' => 27, 'name' => 'Otro'],
            ['commune_id' => 28, 'name' => 'Otro'],
            ['commune_id' => 29, 'name' => 'Otro'],
            ['commune_id' => 30, 'name' => 'Otro'],
            ['commune_id' => 31, 'name' => 'Otro'],
            ['commune_id' => 32, 'name' => 'Otro'],
            ['commune_id' => 33, 'name' => 'Otro'],
            ['commune_id' => 34, 'name' => 'Otro'],
            ['commune_id' => 35, 'name' => 'Otro'],
            ['commune_id' => 36, 'name' => 'Otro'],
            ['commune_id' => 37, 'name' => 'Otro'],
            ['commune_id' => 38, 'name' => 'Otro'],
            ['commune_id' => 39, 'name' => 'Otro'],
            ['commune_id' => 40, 'name' => 'Otro'],
            ['commune_id' => 41, 'name' => 'Otro'],
            ['commune_id' => 42, 'name' => 'Otro'],
            ['commune_id' => 43, 'name' => 'Otro'],
            ['commune_id' => 44, 'name' => 'Otro'],
            ['commune_id' => 45, 'name' => 'Otro'],
            ['commune_id' => 46, 'name' => 'Otro'],
            ['commune_id' => 47, 'name' => 'Otro'],
            ['commune_id' => 48, 'name' => 'Otro'],
            ['commune_id' => 49, 'name' => 'Otro'],
            ['commune_id' => 50, 'name' => 'Otro'],
            ['commune_id' => 51, 'name' => 'Otro'],
            ['commune_id' => 52, 'name' => 'Otro'],
            ['commune_id' => 53, 'name' => 'Otro'],
            ['commune_id' => 54, 'name' => 'Otro'],
            ['commune_id' => 55, 'name' => 'Otro'],
            ['commune_id' => 56, 'name' => 'Otro'],
            ['commune_id' => 57, 'name' => 'Otro'],
            ['commune_id' => 58, 'name' => 'Otro'],
            ['commune_id' => 59, 'name' => 'Otro'],
            ['commune_id' => 60, 'name' => 'Otro'],
            ['commune_id' => 61, 'name' => 'Otro'],
            ['commune_id' => 62, 'name' => 'Otro'],
            ['commune_id' => 63, 'name' => 'Otro'],
            ['commune_id' => 64, 'name' => 'Otro'],
            ['commune_id' => 65, 'name' => 'Otro'],
            ['commune_id' => 66, 'name' => 'Otro'],
            ['commune_id' => 67, 'name' => 'Otro'],
            ['commune_id' => 68, 'name' => 'Otro'],
            ['commune_id' => 69, 'name' => 'Otro'],
            ['commune_id' => 70, 'name' => 'Otro'],
            ['commune_id' => 71, 'name' => 'Otro'],
            ['commune_id' => 72, 'name' => 'Otro'],
            ['commune_id' => 73, 'name' => 'Otro'],
            ['commune_id' => 74, 'name' => 'Otro'],
            ['commune_id' => 75, 'name' => 'Otro'],
            ['commune_id' => 76, 'name' => 'Otro'],
            ['commune_id' => 77, 'name' => 'Otro'],
            ['commune_id' => 78, 'name' => 'Otro'],
            ['commune_id' => 79, 'name' => 'Otro'],
            ['commune_id' => 80, 'name' => 'Otro'],
            ['commune_id' => 81, 'name' => 'Otro'],
            ['commune_id' => 82, 'name' => 'Otro'],
            ['commune_id' => 83, 'name' => 'Otro'],
            ['commune_id' => 84, 'name' => 'Otro'],
            ['commune_id' => 85, 'name' => 'Otro'],
            ['commune_id' => 86, 'name' => 'Otro'],
            ['commune_id' => 87, 'name' => 'Otro'],
            ['commune_id' => 88, 'name' => 'Otro'],
            ['commune_id' => 89, 'name' => 'Otro'],
            ['commune_id' => 90, 'name' => 'Otro'],
            ['commune_id' => 91, 'name' => 'Otro'],
            ['commune_id' => 92, 'name' => 'Otro'],
            ['commune_id' => 93, 'name' => 'Otro'],
            ['commune_id' => 94, 'name' => 'Otro'],
            ['commune_id' => 95, 'name' => 'Otro'],
            ['commune_id' => 96, 'name' => 'Otro'],
            ['commune_id' => 97, 'name' => 'Otro'],
            ['commune_id' => 98, 'name' => 'Otro'],
            ['commune_id' => 99, 'name' => 'Otro'],
            ['commune_id' => 100, 'name' => 'Otro'],
            ['commune_id' => 101, 'name' => 'Otro'],
            ['commune_id' => 102, 'name' => 'Otro'],
            ['commune_id' => 103, 'name' => 'Otro'],
            ['commune_id' => 104, 'name' => 'Otro'],
            ['commune_id' => 105, 'name' => 'Otro'],
            ['commune_id' => 106, 'name' => 'Otro'],
            ['commune_id' => 107, 'name' => 'Otro'],
            ['commune_id' => 108, 'name' => 'Otro'],
            ['commune_id' => 109, 'name' => 'Otro'],
            ['commune_id' => 110, 'name' => 'Otro'],
            ['commune_id' => 111, 'name' => 'Otro'],
            ['commune_id' => 112, 'name' => 'Otro'],
            ['commune_id' => 113, 'name' => 'Otro'],
            ['commune_id' => 114, 'name' => 'Otro'],
            ['commune_id' => 115, 'name' => 'Otro'],
            ['commune_id' => 116, 'name' => 'Otro'],
            ['commune_id' => 117, 'name' => 'Otro'],
            ['commune_id' => 118, 'name' => 'Otro'],
            ['commune_id' => 119, 'name' => 'Otro'],
            ['commune_id' => 120, 'name' => 'Otro'],
            ['commune_id' => 121, 'name' => 'Otro'],
            ['commune_id' => 122, 'name' => 'Otro'],
            ['commune_id' => 123, 'name' => 'Otro'],
            ['commune_id' => 124, 'name' => 'Otro'],
            ['commune_id' => 125, 'name' => 'Otro'],
            ['commune_id' => 126, 'name' => 'Otro'],
            ['commune_id' => 127, 'name' => 'Otro'],
            ['commune_id' => 128, 'name' => 'Otro'],
            ['commune_id' => 129, 'name' => 'Otro'],
            ['commune_id' => 130, 'name' => 'Otro'],
            ['commune_id' => 131, 'name' => 'Otro'],
            ['commune_id' => 132, 'name' => 'Otro'],
            ['commune_id' => 133, 'name' => 'Otro'],
            ['commune_id' => 134, 'name' => 'Otro'],
            ['commune_id' => 135, 'name' => 'Otro'],
            ['commune_id' => 136, 'name' => 'Otro'],
            ['commune_id' => 137, 'name' => 'Otro'],
            ['commune_id' => 138, 'name' => 'Otro'],
            ['commune_id' => 139, 'name' => 'Otro'],
            ['commune_id' => 140, 'name' => 'Otro'],
            ['commune_id' => 141, 'name' => 'Otro'],
            ['commune_id' => 142, 'name' => 'Otro'],
            ['commune_id' => 143, 'name' => 'Otro'],
            ['commune_id' => 144, 'name' => 'Otro'],
            ['commune_id' => 145, 'name' => 'Otro'],
            ['commune_id' => 146, 'name' => 'Otro'],
            ['commune_id' => 147, 'name' => 'Otro'],
            ['commune_id' => 148, 'name' => 'Otro'],
            ['commune_id' => 149, 'name' => 'Otro'],
            ['commune_id' => 150, 'name' => 'Otro'],
            ['commune_id' => 151, 'name' => 'Otro'],
            ['commune_id' => 152, 'name' => 'Otro'],
            ['commune_id' => 153, 'name' => 'Otro'],
            ['commune_id' => 154, 'name' => 'Otro'],
            ['commune_id' => 155, 'name' => 'Otro'],
            ['commune_id' => 156, 'name' => 'Otro'],
            ['commune_id' => 157, 'name' => 'Otro'],
            ['commune_id' => 158, 'name' => 'Otro'],
            ['commune_id' => 159, 'name' => 'Otro'],
            ['commune_id' => 160, 'name' => 'Otro'],
            ['commune_id' => 161, 'name' => 'Otro'],
            ['commune_id' => 162, 'name' => 'Otro'],
            ['commune_id' => 163, 'name' => 'Otro'],
            ['commune_id' => 164, 'name' => 'Otro'],
            ['commune_id' => 165, 'name' => 'Otro'],
            ['commune_id' => 166, 'name' => 'Otro'],
            ['commune_id' => 167, 'name' => 'Otro'],
            ['commune_id' => 168, 'name' => 'Otro'],
            ['commune_id' => 169, 'name' => 'Otro'],
            ['commune_id' => 170, 'name' => 'Otro'],
            ['commune_id' => 171, 'name' => 'Otro'],
            ['commune_id' => 172, 'name' => 'Otro'],
            ['commune_id' => 173, 'name' => 'Otro'],
            ['commune_id' => 174, 'name' => 'Otro'],
            ['commune_id' => 175, 'name' => 'Otro'],
            ['commune_id' => 176, 'name' => 'Otro'],
            ['commune_id' => 177, 'name' => 'Otro'],
            ['commune_id' => 178, 'name' => 'Otro'],
            ['commune_id' => 179, 'name' => 'Otro'],
            ['commune_id' => 180, 'name' => 'Otro'],
            ['commune_id' => 181, 'name' => 'Otro'],
            ['commune_id' => 182, 'name' => 'Otro'],
            ['commune_id' => 183, 'name' => 'Otro'],
            ['commune_id' => 184, 'name' => 'Otro'],
            ['commune_id' => 185, 'name' => 'Otro'],
            ['commune_id' => 186, 'name' => 'Otro'],
            ['commune_id' => 187, 'name' => 'Otro'],
            ['commune_id' => 188, 'name' => 'Otro'],
            ['commune_id' => 189, 'name' => 'Otro'],
            ['commune_id' => 190, 'name' => 'Otro'],
            ['commune_id' => 191, 'name' => 'Otro'],
            ['commune_id' => 192, 'name' => 'Otro'],
            ['commune_id' => 193, 'name' => 'Otro'],
            ['commune_id' => 194, 'name' => 'Otro'],
            ['commune_id' => 195, 'name' => 'Otro'],
            ['commune_id' => 196, 'name' => 'Otro'],
            ['commune_id' => 197, 'name' => 'Otro'],
            ['commune_id' => 198, 'name' => 'Otro'],
            ['commune_id' => 199, 'name' => 'Otro'],
            ['commune_id' => 200, 'name' => 'Otro'],
            ['commune_id' => 201, 'name' => 'Otro'],
            ['commune_id' => 202, 'name' => 'Otro'],
            ['commune_id' => 203, 'name' => 'Otro'],
            ['commune_id' => 204, 'name' => 'Otro'],
            ['commune_id' => 205, 'name' => 'Otro'],
            ['commune_id' => 206, 'name' => 'Otro'],
            ['commune_id' => 207, 'name' => 'Otro'],
            ['commune_id' => 208, 'name' => 'Otro'],
            ['commune_id' => 209, 'name' => 'Otro'],
            ['commune_id' => 210, 'name' => 'Otro'],
            ['commune_id' => 211, 'name' => 'Otro'],
            ['commune_id' => 212, 'name' => 'Otro'],
            ['commune_id' => 213, 'name' => 'Otro'],
            ['commune_id' => 214, 'name' => 'Otro'],
            ['commune_id' => 215, 'name' => 'Otro'],
            ['commune_id' => 216, 'name' => 'Otro'],
            ['commune_id' => 217, 'name' => 'Otro'],
            ['commune_id' => 218, 'name' => 'Otro'],
            ['commune_id' => 219, 'name' => 'Otro'],
            ['commune_id' => 220, 'name' => 'Otro'],
            ['commune_id' => 221, 'name' => 'Otro'],
            ['commune_id' => 222, 'name' => 'Otro'],
            ['commune_id' => 223, 'name' => 'Otro'],
            ['commune_id' => 224, 'name' => 'Otro'],
            ['commune_id' => 225, 'name' => 'Otro'],
            ['commune_id' => 226, 'name' => 'Otro'],
            ['commune_id' => 227, 'name' => 'Otro'],
            ['commune_id' => 228, 'name' => 'Otro'],
            ['commune_id' => 229, 'name' => 'Otro'],
            ['commune_id' => 230, 'name' => 'Otro'],
            ['commune_id' => 231, 'name' => 'Otro'],
            ['commune_id' => 232, 'name' => 'Otro'],
            ['commune_id' => 233, 'name' => 'Otro'],
            ['commune_id' => 234, 'name' => 'Otro'],
            ['commune_id' => 235, 'name' => 'Otro'],
            ['commune_id' => 236, 'name' => 'Otro'],
            ['commune_id' => 237, 'name' => 'Otro'],
            ['commune_id' => 238, 'name' => 'Otro'],
            ['commune_id' => 239, 'name' => 'Otro'],
            ['commune_id' => 240, 'name' => 'Otro'],
            ['commune_id' => 241, 'name' => 'Otro'],
            ['commune_id' => 242, 'name' => 'Otro'],
            ['commune_id' => 243, 'name' => 'Otro'],
            ['commune_id' => 244, 'name' => 'Otro'],
            ['commune_id' => 245, 'name' => 'Otro'],
            ['commune_id' => 246, 'name' => 'Otro'],
            ['commune_id' => 247, 'name' => 'Otro'],
            ['commune_id' => 248, 'name' => 'Otro'],
            ['commune_id' => 249, 'name' => 'Otro'],
            ['commune_id' => 250, 'name' => 'Otro'],
            ['commune_id' => 251, 'name' => 'Otro'],
            ['commune_id' => 252, 'name' => 'Otro'],
            ['commune_id' => 253, 'name' => 'Otro'],
            ['commune_id' => 254, 'name' => 'Otro'],
            ['commune_id' => 255, 'name' => 'Otro'],
            ['commune_id' => 256, 'name' => 'Otro'],
            ['commune_id' => 257, 'name' => 'Otro'],
            ['commune_id' => 258, 'name' => 'Otro'],
            ['commune_id' => 259, 'name' => 'Otro'],
            ['commune_id' => 260, 'name' => 'Otro'],
            ['commune_id' => 261, 'name' => 'Otro'],
            ['commune_id' => 262, 'name' => 'Otro'],
            ['commune_id' => 263, 'name' => 'Otro'],
            ['commune_id' => 264, 'name' => 'Otro'],
            ['commune_id' => 265, 'name' => 'Otro'],
            ['commune_id' => 266, 'name' => 'Otro'],
            ['commune_id' => 267, 'name' => 'Otro'],
            ['commune_id' => 268, 'name' => 'Otro'],
            ['commune_id' => 269, 'name' => 'Otro'],
            ['commune_id' => 270, 'name' => 'Otro'],
            ['commune_id' => 271, 'name' => 'Otro'],
            ['commune_id' => 272, 'name' => 'Otro'],
            ['commune_id' => 273, 'name' => 'Otro'],
            ['commune_id' => 274, 'name' => 'Otro'],
            ['commune_id' => 275, 'name' => 'Otro'],
            ['commune_id' => 276, 'name' => 'Otro'],
            ['commune_id' => 277, 'name' => 'Otro'],
            ['commune_id' => 278, 'name' => 'Otro'],
            ['commune_id' => 279, 'name' => 'Otro'],
            ['commune_id' => 280, 'name' => 'Otro'],
            ['commune_id' => 281, 'name' => 'Otro'],
            ['commune_id' => 282, 'name' => 'Otro'],
            ['commune_id' => 283, 'name' => 'Otro'],
            ['commune_id' => 284, 'name' => 'Otro'],
            ['commune_id' => 285, 'name' => 'Otro'],
            ['commune_id' => 286, 'name' => 'Otro'],
            ['commune_id' => 287, 'name' => 'Otro'],
            ['commune_id' => 288, 'name' => 'Otro'],
            ['commune_id' => 289, 'name' => 'Otro'],
            ['commune_id' => 290, 'name' => 'Otro'],
            ['commune_id' => 291, 'name' => 'Otro'],
            ['commune_id' => 292, 'name' => 'Otro'],
            ['commune_id' => 293, 'name' => 'Otro'],
            ['commune_id' => 294, 'name' => 'Otro'],
            ['commune_id' => 295, 'name' => 'Otro'],
            ['commune_id' => 296, 'name' => 'Otro'],
            ['commune_id' => 297, 'name' => 'Otro'],
            ['commune_id' => 298, 'name' => 'Otro'],
            ['commune_id' => 299, 'name' => 'Otro'],
            ['commune_id' => 300, 'name' => 'Otro'],
            ['commune_id' => 301, 'name' => 'Otro'],
            ['commune_id' => 302, 'name' => 'Otro'],
            ['commune_id' => 303, 'name' => 'Otro'],
            ['commune_id' => 304, 'name' => 'Otro'],
            ['commune_id' => 305, 'name' => 'Otro'],
            ['commune_id' => 306, 'name' => 'Otro'],
            ['commune_id' => 307, 'name' => 'Otro'],
            ['commune_id' => 308, 'name' => 'Otro'],
            ['commune_id' => 309, 'name' => 'Otro'],
            ['commune_id' => 310, 'name' => 'Otro'],
            ['commune_id' => 311, 'name' => 'Otro'],
            ['commune_id' => 312, 'name' => 'Otro'],
            ['commune_id' => 313, 'name' => 'Otro'],
            ['commune_id' => 314, 'name' => 'Otro'],
            ['commune_id' => 315, 'name' => 'Otro'],
            ['commune_id' => 316, 'name' => 'Otro'],
            ['commune_id' => 317, 'name' => 'Otro'],
            ['commune_id' => 318, 'name' => 'Otro'],
            ['commune_id' => 319, 'name' => 'Otro'],
            ['commune_id' => 320, 'name' => 'Otro'],
            ['commune_id' => 321, 'name' => 'Otro'],
            ['commune_id' => 322, 'name' => 'Otro'],
            ['commune_id' => 323, 'name' => 'Otro'],
            ['commune_id' => 324, 'name' => 'Otro'],
            ['commune_id' => 325, 'name' => 'Otro'],
            ['commune_id' => 326, 'name' => 'Otro'],
            ['commune_id' => 327, 'name' => 'Otro'],
            ['commune_id' => 328, 'name' => 'Otro'],
            ['commune_id' => 329, 'name' => 'Otro'],
            ['commune_id' => 330, 'name' => 'Otro'],
            ['commune_id' => 331, 'name' => 'Otro'],
            ['commune_id' => 332, 'name' => 'Otro'],
            ['commune_id' => 333, 'name' => 'Otro'],
            ['commune_id' => 334, 'name' => 'Otro'],
            ['commune_id' => 335, 'name' => 'Otro'],
            ['commune_id' => 336, 'name' => 'Otro'],
            ['commune_id' => 337, 'name' => 'Otro'],
            ['commune_id' => 338, 'name' => 'Otro'],
            ['commune_id' => 339, 'name' => 'Otro'],
            ['commune_id' => 340, 'name' => 'Otro'],
            ['commune_id' => 341, 'name' => 'Otro'],
            ['commune_id' => 342, 'name' => 'Otro'],
            ['commune_id' => 343, 'name' => 'Otro'],
            ['commune_id' => 344, 'name' => 'Otro'],
            ['commune_id' => 345, 'name' => 'Otro'],
            ['commune_id' => 346, 'name' => 'Otro'],
            ['commune_id' => 347, 'name' => 'Otro'],
            ['commune_id' => 348, 'name' => 'Otro'],
            ['commune_id' => 349, 'name' => 'Otro'],
            ['commune_id' => 350, 'name' => 'Otro'],
            ['commune_id' => 351, 'name' => 'Otro'],
            ['commune_id' => 352, 'name' => 'Otro'],
            ['commune_id' => 353, 'name' => 'Otro'],
            ['commune_id' => 354, 'name' => 'Otro'],
            ['commune_id' => 355, 'name' => 'Otro'],
            ['commune_id' => 356, 'name' => 'Otro'],
            ['commune_id' => 357, 'name' => 'Otro'],
            ['commune_id' => 358, 'name' => 'Otro'],
            ['commune_id' => 359, 'name' => 'Otro'],
            ['commune_id' => 360, 'name' => 'Otro'],
            ['commune_id' => 361, 'name' => 'Otro'],
            ['commune_id' => 362, 'name' => 'Otro'],
            ['commune_id' => 363, 'name' => 'Otro'],
            ['commune_id' => 364, 'name' => 'Otro'],
            ['commune_id' => 365, 'name' => 'Otro'],
            ['commune_id' => 366, 'name' => 'Otro'],
            ['commune_id' => 367, 'name' => 'Otro'],
            ['commune_id' => 368, 'name' => 'Otro'],
            ['commune_id' => 369, 'name' => 'Otro'],
            ['commune_id' => 370, 'name' => 'Otro'],
            ['commune_id' => 371, 'name' => 'Otro'],
            ['commune_id' => 372, 'name' => 'Otro'],
            ['commune_id' => 373, 'name' => 'Otro'],
            ['commune_id' => 374, 'name' => 'Otro'],
            ['commune_id' => 375, 'name' => 'Otro'],
            ['commune_id' => 376, 'name' => 'Otro'],
            ['commune_id' => 377, 'name' => 'Otro'],
            ['commune_id' => 378, 'name' => 'Otro'],
            ['commune_id' => 379, 'name' => 'Otro'],
            ['commune_id' => 380, 'name' => 'Otro'],
            ['commune_id' => 381, 'name' => 'Otro'],
            ['commune_id' => 382, 'name' => 'Otro'],
            ['commune_id' => 383, 'name' => 'Otro'],
            ['commune_id' => 384, 'name' => 'Otro'],
            ['commune_id' => 385, 'name' => 'Otro'],
            ['commune_id' => 386, 'name' => 'Otro'],
            ['commune_id' => 387, 'name' => 'Otro'],
            ['commune_id' => 388, 'name' => 'Otro'],
            ['commune_id' => 389, 'name' => 'Otro'],
            ['commune_id' => 390, 'name' => 'Otro'],
            ['commune_id' => 391, 'name' => 'Otro'],
            ['commune_id' => 392, 'name' => 'Otro'],
            ['commune_id' => 393, 'name' => 'Otro'],
            ['commune_id' => 394, 'name' => 'Otro'],
            ['commune_id' => 395, 'name' => 'Otro'],
            ['commune_id' => 396, 'name' => 'Otro'],
            ['commune_id' => 397, 'name' => 'Otro'],
            ['commune_id' => 398, 'name' => 'Otro'],
            ['commune_id' => 399, 'name' => 'Otro'],
            ['commune_id' => 400, 'name' => 'Otro'],
            ['commune_id' => 401, 'name' => 'Otro'],
            ['commune_id' => 402, 'name' => 'Otro'],
            ['commune_id' => 403, 'name' => 'Otro'],
            ['commune_id' => 404, 'name' => 'Otro'],
            ['commune_id' => 405, 'name' => 'Otro'],
            ['commune_id' => 406, 'name' => 'Otro'],
            ['commune_id' => 407, 'name' => 'Otro'],
            ['commune_id' => 408, 'name' => 'Otro'],
            ['commune_id' => 409, 'name' => 'Otro'],
            ['commune_id' => 410, 'name' => 'Otro'],
            ['commune_id' => 411, 'name' => 'Otro'],
            ['commune_id' => 412, 'name' => 'Otro'],
            ['commune_id' => 413, 'name' => 'Otro'],
            ['commune_id' => 414, 'name' => 'Otro'],
            ['commune_id' => 415, 'name' => 'Otro'],
            ['commune_id' => 416, 'name' => 'Otro'],
            ['commune_id' => 417, 'name' => 'Otro'],
            ['commune_id' => 418, 'name' => 'Otro'],
            ['commune_id' => 419, 'name' => 'Otro'],
            ['commune_id' => 420, 'name' => 'Otro'],
            ['commune_id' => 421, 'name' => 'Otro'],
            ['commune_id' => 422, 'name' => 'Otro'],
            ['commune_id' => 423, 'name' => 'Otro'],
            ['commune_id' => 424, 'name' => 'Otro'],
            ['commune_id' => 425, 'name' => 'Otro'],
            ['commune_id' => 426, 'name' => 'Otro'],
            ['commune_id' => 427, 'name' => 'Otro'],
            ['commune_id' => 428, 'name' => 'Otro'],
            ['commune_id' => 429, 'name' => 'Otro'],
            ['commune_id' => 430, 'name' => 'Otro'],
            ['commune_id' => 431, 'name' => 'Otro'],
            ['commune_id' => 432, 'name' => 'Otro'],
            ['commune_id' => 433, 'name' => 'Otro'],
            ['commune_id' => 434, 'name' => 'Otro'],
            ['commune_id' => 435, 'name' => 'Otro'],
            ['commune_id' => 436, 'name' => 'Otro'],
            ['commune_id' => 437, 'name' => 'Otro'],
            ['commune_id' => 438, 'name' => 'Otro'],
            ['commune_id' => 439, 'name' => 'Otro'],
            ['commune_id' => 440, 'name' => 'Otro'],
            ['commune_id' => 441, 'name' => 'Otro'],
            ['commune_id' => 442, 'name' => 'Otro'],
            ['commune_id' => 443, 'name' => 'Otro'],
            ['commune_id' => 444, 'name' => 'Otro'],
            ['commune_id' => 445, 'name' => 'Otro'],
            ['commune_id' => 446, 'name' => 'Otro'],
            ['commune_id' => 447, 'name' => 'Otro'],
            ['commune_id' => 448, 'name' => 'Otro'],
            ['commune_id' => 449, 'name' => 'Otro'],
            ['commune_id' => 450, 'name' => 'Otro'],
            ['commune_id' => 451, 'name' => 'Otro'],
            ['commune_id' => 452, 'name' => 'Otro'],
            ['commune_id' => 453, 'name' => 'Otro'],
            ['commune_id' => 454, 'name' => 'Otro'],
            ['commune_id' => 455, 'name' => 'Otro'],
            ['commune_id' => 456, 'name' => 'Otro'],
            ['commune_id' => 457, 'name' => 'Otro'],
            ['commune_id' => 458, 'name' => 'Otro'],
            ['commune_id' => 459, 'name' => 'Otro'],
            ['commune_id' => 460, 'name' => 'Otro'],
            ['commune_id' => 461, 'name' => 'Otro'],
            ['commune_id' => 462, 'name' => 'Otro'],
            ['commune_id' => 463, 'name' => 'Otro'],
            ['commune_id' => 464, 'name' => 'Otro'],
            ['commune_id' => 465, 'name' => 'Otro'],
            ['commune_id' => 466, 'name' => 'Otro'],
            ['commune_id' => 467, 'name' => 'Otro'],
            ['commune_id' => 468, 'name' => 'Otro'],
            ['commune_id' => 469, 'name' => 'Otro'],
            ['commune_id' => 470, 'name' => 'Otro'],
            ['commune_id' => 471, 'name' => 'Otro'],
            ['commune_id' => 472, 'name' => 'Otro'],
            ['commune_id' => 473, 'name' => 'Otro'],
            ['commune_id' => 474, 'name' => 'Otro'],
            ['commune_id' => 475, 'name' => 'Otro'],
            ['commune_id' => 476, 'name' => 'Otro'],
            ['commune_id' => 477, 'name' => 'Otro'],
            ['commune_id' => 478, 'name' => 'Otro'],
            ['commune_id' => 479, 'name' => 'Otro'],
            ['commune_id' => 480, 'name' => 'Otro'],
            ['commune_id' => 481, 'name' => 'Otro'],
            ['commune_id' => 482, 'name' => 'Otro'],
            ['commune_id' => 483, 'name' => 'Otro'],
            ['commune_id' => 484, 'name' => 'Otro'],
            ['commune_id' => 485, 'name' => 'Otro'],
            ['commune_id' => 486, 'name' => 'Otro'],
            ['commune_id' => 487, 'name' => 'Otro'],
            ['commune_id' => 488, 'name' => 'Otro'],
            ['commune_id' => 489, 'name' => 'Otro'],
            ['commune_id' => 490, 'name' => 'Otro'],
            ['commune_id' => 491, 'name' => 'Otro'],
            ['commune_id' => 492, 'name' => 'Otro'],
            ['commune_id' => 493, 'name' => 'Otro'],
            ['commune_id' => 494, 'name' => 'Otro'],
            ['commune_id' => 495, 'name' => 'Otro'],
            ['commune_id' => 496, 'name' => 'Otro'],
            ['commune_id' => 497, 'name' => 'Otro'],
            ['commune_id' => 498, 'name' => 'Otro'],
            ['commune_id' => 499, 'name' => 'Otro'],
            ['commune_id' => 500, 'name' => 'Otro'],
            ['commune_id' => 501, 'name' => 'Otro'],
            ['commune_id' => 502, 'name' => 'Otro'],
            ['commune_id' => 503, 'name' => 'Otro'],
            ['commune_id' => 504, 'name' => 'Otro'],
            ['commune_id' => 505, 'name' => 'Otro'],
            ['commune_id' => 506, 'name' => 'Otro'],
            ['commune_id' => 507, 'name' => 'Otro'],
            ['commune_id' => 508, 'name' => 'Otro'],
            ['commune_id' => 509, 'name' => 'Otro'],
            ['commune_id' => 510, 'name' => 'Otro'],
            ['commune_id' => 511, 'name' => 'Otro'],
            ['commune_id' => 512, 'name' => 'Otro'],
            ['commune_id' => 513, 'name' => 'Otro'],
            ['commune_id' => 514, 'name' => 'Otro'],
            ['commune_id' => 515, 'name' => 'Otro'],
            ['commune_id' => 516, 'name' => 'Otro'],
            ['commune_id' => 517, 'name' => 'Otro'],
            ['commune_id' => 518, 'name' => 'Otro'],
            ['commune_id' => 519, 'name' => 'Otro'],
            ['commune_id' => 520, 'name' => 'Otro'],
            ['commune_id' => 521, 'name' => 'Otro'],
            ['commune_id' => 522, 'name' => 'Otro'],
            ['commune_id' => 523, 'name' => 'Otro'],
            ['commune_id' => 524, 'name' => 'Otro'],
            ['commune_id' => 525, 'name' => 'Otro'],
            ['commune_id' => 526, 'name' => 'Otro'],
            ['commune_id' => 527, 'name' => 'Otro'],
            ['commune_id' => 528, 'name' => 'Otro'],
            ['commune_id' => 529, 'name' => 'Otro'],
            ['commune_id' => 530, 'name' => 'Otro'],
            ['commune_id' => 531, 'name' => 'Otro'],
            ['commune_id' => 532, 'name' => 'Otro'],
            ['commune_id' => 533, 'name' => 'Otro'],
            ['commune_id' => 534, 'name' => 'Otro'],
            ['commune_id' => 535, 'name' => 'Otro'],
            ['commune_id' => 536, 'name' => 'Otro'],
            ['commune_id' => 537, 'name' => 'Otro'],
            ['commune_id' => 538, 'name' => 'Otro'],
            ['commune_id' => 539, 'name' => 'Otro'],
            ['commune_id' => 540, 'name' => 'Otro'],
            ['commune_id' => 541, 'name' => 'Otro'],
            ['commune_id' => 542, 'name' => 'Otro'],
            ['commune_id' => 543, 'name' => 'Otro'],
            ['commune_id' => 544, 'name' => 'Otro'],
            ['commune_id' => 545, 'name' => 'Otro'],
            ['commune_id' => 546, 'name' => 'Otro'],
            ['commune_id' => 547, 'name' => 'Otro'],
            ['commune_id' => 548, 'name' => 'Otro'],
            ['commune_id' => 549, 'name' => 'Otro'],
            ['commune_id' => 550, 'name' => 'Otro'],
            ['commune_id' => 551, 'name' => 'Otro'],
            ['commune_id' => 552, 'name' => 'Otro'],
            ['commune_id' => 553, 'name' => 'Otro'],
            ['commune_id' => 554, 'name' => 'Otro'],
            ['commune_id' => 555, 'name' => 'Otro'],
            ['commune_id' => 556, 'name' => 'Otro'],
            ['commune_id' => 557, 'name' => 'Otro'],
            ['commune_id' => 558, 'name' => 'Otro'],
            ['commune_id' => 559, 'name' => 'Otro'],
            ['commune_id' => 560, 'name' => 'Otro'],
            ['commune_id' => 561, 'name' => 'Otro'],
            ['commune_id' => 562, 'name' => 'Otro'],
            ['commune_id' => 563, 'name' => 'Otro'],
            ['commune_id' => 564, 'name' => 'Otro'],
            ['commune_id' => 565, 'name' => 'Otro'],
            ['commune_id' => 566, 'name' => 'Otro'],
            ['commune_id' => 567, 'name' => 'Otro'],
            ['commune_id' => 568, 'name' => 'Otro'],
            ['commune_id' => 569, 'name' => 'Otro'],
            ['commune_id' => 570, 'name' => 'Otro'],
            ['commune_id' => 571, 'name' => 'Otro'],
            ['commune_id' => 572, 'name' => 'Otro'],
            ['commune_id' => 573, 'name' => 'Otro'],
            ['commune_id' => 574, 'name' => 'Otro'],
            ['commune_id' => 575, 'name' => 'Otro'],
            ['commune_id' => 576, 'name' => 'Otro'],
            ['commune_id' => 577, 'name' => 'Otro'],
            ['commune_id' => 578, 'name' => 'Otro'],
            ['commune_id' => 579, 'name' => 'Otro'],
            ['commune_id' => 580, 'name' => 'Otro'],
            ['commune_id' => 581, 'name' => 'Otro'],
            ['commune_id' => 582, 'name' => 'Otro'],
            ['commune_id' => 583, 'name' => 'Otro'],
            ['commune_id' => 584, 'name' => 'Otro'],
            ['commune_id' => 585, 'name' => 'Otro'],
            ['commune_id' => 586, 'name' => 'Otro'],
            ['commune_id' => 587, 'name' => 'Otro'],
            ['commune_id' => 588, 'name' => 'Otro'],
            ['commune_id' => 589, 'name' => 'Otro'],
            ['commune_id' => 590, 'name' => 'Otro'],
            ['commune_id' => 591, 'name' => 'Otro'],
            ['commune_id' => 592, 'name' => 'Otro'],
            ['commune_id' => 593, 'name' => 'Otro'],
            ['commune_id' => 594, 'name' => 'Otro'],
            ['commune_id' => 595, 'name' => 'Otro'],
            ['commune_id' => 596, 'name' => 'Otro'],
            ['commune_id' => 597, 'name' => 'Otro'],
            ['commune_id' => 598, 'name' => 'Otro'],
            ['commune_id' => 599, 'name' => 'Otro'],
            ['commune_id' => 600, 'name' => 'Otro'],
            ['commune_id' => 601, 'name' => 'Otro'],
            ['commune_id' => 602, 'name' => 'Otro'],
            ['commune_id' => 603, 'name' => 'Otro'],
            ['commune_id' => 604, 'name' => 'Otro'],
            ['commune_id' => 605, 'name' => 'Otro'],
            ['commune_id' => 606, 'name' => 'Santa Inés'],
            ['commune_id' => 606, 'name' => 'Cándido Leguízamo'],
            ['commune_id' => 606, 'name' => 'Las Mercedes'],
            ['commune_id' => 606, 'name' => 'Las Ferias'],
            ['commune_id' => 606, 'name' => 'Chícalá'],
            ['commune_id' => 606, 'name' => 'Minuto de Dios Norte'],
            ['commune_id' => 606, 'name' => 'La inmaculada'],
            ['commune_id' => 606, 'name' => 'Villa del Río'],
            ['commune_id' => 606, 'name' => 'Rodrigo Lara Bonilla'],
            ['commune_id' => 606, 'name' => 'Conjunto La Magdalena'],
            ['commune_id' => 606, 'name' => 'Acrópolis'],
            ['commune_id' => 606, 'name' => 'Los Elisios'],
            ['commune_id' => 606, 'name' => 'California'],
            ['commune_id' => 606, 'name' => 'Media Luna'],
            ['commune_id' => 606, 'name' => 'San Nicolás'],
            ['commune_id' => 606, 'name' => 'Los Andaquíes'],
            ['commune_id' => 606, 'name' => 'Los Dujos'],
            ['commune_id' => 606, 'name' => 'San Silvestre'],
            ['commune_id' => 606, 'name' => 'Carlos Pizarro'],
            ['commune_id' => 606, 'name' => 'El Triángulo'],
            ['commune_id' => 606, 'name' => 'José Martí'],
            ['commune_id' => 606, 'name' => 'Pigoanza'],
            ['commune_id' => 606, 'name' => 'MadrigaL Conarvar'],
            ['commune_id' => 606, 'name' => 'Colmenar y sus etapas'],
            ['commune_id' => 606, 'name' => 'Villa Magdalena Norte'],
            ['commune_id' => 606, 'name' => 'La Fortaleza'],
            ['commune_id' => 606, 'name' => 'Bajo Chicalá'],
            ['commune_id' => 606, 'name' => 'Mansiones del Norte'],
            ['commune_id' => 606, 'name' => 'Ciudadela Carlos Pízarro. Ciudadela Comfamiliar'],
            ['commune_id' => 606, 'name' => 'Torres de la Camila'],
            ['commune_id' => 606, 'name' => 'Portal de San Felipe'],
            ['commune_id' => 606, 'name' => 'Balcones de la Riviera'],
            ['commune_id' => 606, 'name' => 'Riviera I y II'],
            ['commune_id' => 606, 'name' => 'Portales de Varanta'],
            ['commune_id' => 606, 'name' => 'Los Dujos'],
            ['commune_id' => 606, 'name' => 'Minuto de Dios'],
            ['commune_id' => 606, 'name' => 'La Vorágine.'],

            ['commune_id' => 607, 'name' => 'Aeropuerto'],
            ['commune_id' => 607, 'name' => 'Álvaro Sánchez Silva'],
            ['commune_id' => 607, 'name' => 'Santa Lucía'],
            ['commune_id' => 607, 'name' => 'Santa Clara'],
            ['commune_id' => 607, 'name' => 'Los Cámbulos'],
            ['commune_id' => 607, 'name' => 'Los Molinos'],
            ['commune_id' => 607, 'name' => 'Las Granjas'],
            ['commune_id' => 607, 'name' => 'Bosques de Tamarindo'],
            ['commune_id' => 607, 'name' => 'Santa Mónica'],
            ['commune_id' => 607, 'name' => 'El Prado'],
            ['commune_id' => 607, 'name' => 'Los Pinos'],
            ['commune_id' => 607, 'name' => 'Alamos Norte'],
            ['commune_id' => 607, 'name' => 'El Cortijo'],
            ['commune_id' => 607, 'name' => 'Municipal'],
            ['commune_id' => 607, 'name' => 'Villa Cecilia'],
            ['commune_id' => 607, 'name' => 'Los Andes'],
            ['commune_id' => 607, 'name' => 'Villa Milena'],
            ['commune_id' => 607, 'name' => 'Gualanday'],
            ['commune_id' => 607, 'name' => 'Villa Aurora'],
            ['commune_id' => 607, 'name' => 'Villa Urbe'],
            ['commune_id' => 607, 'name' => 'Versalles'],
            ['commune_id' => 607, 'name' => 'Santa Ana'],
            ['commune_id' => 607, 'name' => 'Conjunto Camino Real'],
            ['commune_id' => 607, 'name' => 'Conjunto Málaga'],
            ['commune_id' => 607, 'name' => 'Portal de la Calleja'],
            ['commune_id' => 607, 'name' => 'El Rosal. Las Villas'],
            ['commune_id' => 607, 'name' => 'Villa del Prado'],
            ['commune_id' => 607, 'name' => 'Villa Flor'],
            ['commune_id' => 607, 'name' => 'Villa Esmeralda'],
            ['commune_id' => 607, 'name' => 'Torres de Varegal Cataluña'],
            ['commune_id' => 607, 'name' => 'San Diego'],

            ['commune_id' => 608, 'name' => 'El Lago'],
            ['commune_id' => 608, 'name' => 'Caracolí'],
            ['commune_id' => 608, 'name' => 'San Vicente de Paúl'],
            ['commune_id' => 608, 'name' => 'La Cordialidad'],
            ['commune_id' => 608, 'name' => 'Guillermo Plazas Alcid'],
            ['commune_id' => 608, 'name' => 'Reinaldo Matiz Trujillo'],
            ['commune_id' => 608, 'name' => 'Rojas Trujillo'],
            ['commune_id' => 608, 'name' => 'Las Delicias'],
            ['commune_id' => 608, 'name' => 'Sevilla'],
            ['commune_id' => 608, 'name' => 'Las Ceibas'],
            ['commune_id' => 608, 'name' => 'Quirinal'],
            ['commune_id' => 608, 'name' => 'José Eustasio Rivera'],
            ['commune_id' => 608, 'name' => 'Tenerife'],
            ['commune_id' => 608, 'name' => 'Campo Núñez'],
            ['commune_id' => 608, 'name' => 'La Torna'],
            ['commune_id' => 608, 'name' => 'Chapinero'],
            ['commune_id' => 608, 'name' => 'Santa Librada'],
            ['commune_id' => 608, 'name' => 'Los Samanes'],
            ['commune_id' => 608, 'name' => 'Villa Patricia'],
            ['commune_id' => 608, 'name' => 'La Estrella'],
            ['commune_id' => 608, 'name' => 'Las Ceibitas'],
            ['commune_id' => 608, 'name' => 'Conjunto Brisas del Magdalena'],
            ['commune_id' => 608, 'name' => 'Los Profesionales'],
            ['commune_id' => 608, 'name' => 'Alcalá.'],

            ['commune_id' => 609, 'name' => 'Bonilla'],
            ['commune_id' => 609, 'name' => 'Los Mártires'],
            ['commune_id' => 609, 'name' => 'El Centro'],
            ['commune_id' => 609, 'name' => 'San Pedro'],
            ['commune_id' => 609, 'name' => 'Los Almendros'],
            ['commune_id' => 609, 'name' => 'El Estadio'],
            ['commune_id' => 609, 'name' => 'Altico'],
            ['commune_id' => 609, 'name' => 'Modelo'],
            ['commune_id' => 609, 'name' => 'San José'],
            ['commune_id' => 609, 'name' => 'Diego de Ospina'],
            ['commune_id' => 609, 'name' => 'La Unión.'],

            ['commune_id' => 610, 'name' => 'Primero de Mayo'],
            ['commune_id' => 610, 'name' => 'La Libertad'],
            ['commune_id' => 610, 'name' => 'Loma de La Cruz'],
            ['commune_id' => 610, 'name' => 'La Colina'],
            ['commune_id' => 610, 'name' => 'Kennedy'],
            ['commune_id' => 610, 'name' => 'Monserrate'],
            ['commune_id' => 610, 'name' => 'Siete de Agosto'],
            ['commune_id' => 610, 'name' => 'San Antonio'],
            ['commune_id' => 610, 'name' => 'La Independencia'],
            ['commune_id' => 610, 'name' => 'El Jardín'],
            ['commune_id' => 610, 'name' => 'Buganviles'],
            ['commune_id' => 610, 'name' => 'La Orquídea'],
            ['commune_id' => 610, 'name' => 'Los Guaduales'],
            ['commune_id' => 610, 'name' => 'Jordán'],
            ['commune_id' => 610, 'name' => 'Faro'],
            ['commune_id' => 610, 'name' => 'Veinte de Julio'],
            ['commune_id' => 610, 'name' => 'Villa Rosa'],
            ['commune_id' => 610, 'name' => 'Independencia Baja'],
            ['commune_id' => 610, 'name' => 'El Vergel Brisas del Avichente'],
            ['commune_id' => 610, 'name' => 'Los Laureles'],
            ['commune_id' => 610, 'name' => 'Sector La Colina'],
            ['commune_id' => 610, 'name' => 'Alto Llano'],
            ['commune_id' => 610, 'name' => 'Villa Café'],
            ['commune_id' => 610, 'name' => 'Altos de la Ferreira'],
            ['commune_id' => 610, 'name' => 'Villa Regina'],
            ['commune_id' => 610, 'name' => 'Alta Vista'],
            ['commune_id' => 610, 'name' => 'Conjunto Altos de Tívoli'],
            ['commune_id' => 610, 'name' => 'Conjunto Aragonés.'],

            ['commune_id' => 611, 'name' => 'Minuto de Dios'],
            ['commune_id' => 611, 'name' => 'Miramar'],
            ['commune_id' => 611, 'name' => 'Andalucía'],
            ['commune_id' => 611, 'name' => 'Alto del Limonar'],
            ['commune_id' => 611, 'name' => 'Emayá'],
            ['commune_id' => 611, 'name' => 'Santa Isabel'],
            ['commune_id' => 611, 'name' => 'La Esperanza'],
            ['commune_id' => 611, 'name' => 'Bogotá'],
            ['commune_id' => 611, 'name' => 'Buenos Aires'],
            ['commune_id' => 611, 'name' => 'Sinaí'],
            ['commune_id' => 611, 'name' => 'José Antonio Galán'],
            ['commune_id' => 611, 'name' => 'Los Nazarenos'],
            ['commune_id' => 611, 'name' => 'Pozo Azul'],
            ['commune_id' => 611, 'name' => 'Loma Linda'],
            ['commune_id' => 611, 'name' => 'Arismendi Mora'],
            ['commune_id' => 611, 'name' => 'Timanco'],
            ['commune_id' => 611, 'name' => 'Bella Vista'],
            ['commune_id' => 611, 'name' => 'El Limonar'],
            ['commune_id' => 611, 'name' => 'Villa Inés'],
            ['commune_id' => 611, 'name' => 'Los Caobos'],
            ['commune_id' => 611, 'name' => 'Manzanares'],
            ['commune_id' => 611, 'name' => 'San Francisco de Asís'],
            ['commune_id' => 611, 'name' => 'Tuquíla'],
            ['commune_id' => 611, 'name' => 'Las Lajas'],
            ['commune_id' => 611, 'name' => 'El Bosque'],
            ['commune_id' => 611, 'name' => 'Sector Santa Isabel'],
            ['commune_id' => 611, 'name' => 'Sector Galán'],
            ['commune_id' => 611, 'name' => 'Sector Bogotá'],
            ['commune_id' => 611, 'name' => 'Canaíma'],
            ['commune_id' => 611, 'name' => 'Conjunto Multifamiliar Los Arrayanes.'],

            ['commune_id' => 612, 'name' => 'Las Brisas'],
            ['commune_id' => 612, 'name' => 'Casa Loma'],
            ['commune_id' => 612, 'name' => 'La Floresta'],
            ['commune_id' => 612, 'name' => 'Ipanema'],
            ['commune_id' => 612, 'name' => 'Casa de Campo'],
            ['commune_id' => 612, 'name' => 'Altamíra'],
            ['commune_id' => 612, 'name' => 'Prado Alto'],
            ['commune_id' => 612, 'name' => 'Casa Blanca'],
            ['commune_id' => 612, 'name' => 'La Gaitana'],
            ['commune_id' => 612, 'name' => 'Calixto Leyva'],
            ['commune_id' => 612, 'name' => 'Buena Vista'],
            ['commune_id' => 612, 'name' => 'Jorge Eliécer Gaitán'],
            ['commune_id' => 612, 'name' => 'Obrero'],
            ['commune_id' => 612, 'name' => 'Ventilador'],
            ['commune_id' => 612, 'name' => 'San Martín'],
            ['commune_id' => 612, 'name' => 'la Juventud'],
            ['commune_id' => 612, 'name' => 'Conjunto Punta del Este'],
            ['commune_id' => 612, 'name' => 'Villa Milena'],
            ['commune_id' => 612, 'name' => 'Santa Faula'],
            ['commune_id' => 612, 'name' => 'Altos de Manzanillo'],
            ['commune_id' => 612, 'name' => 'Gaitana Dos'],
            ['commune_id' => 612, 'name' => 'Conjunto Portal delCampo'],
            ['commune_id' => 612, 'name' => 'Paseo La Castellana'],
            ['commune_id' => 612, 'name' => 'Conjunto lbrres de Bizancio'],
            ['commune_id' => 612, 'name' => 'Antigua'],
            ['commune_id' => 612, 'name' => 'Santorini'],
            ['commune_id' => 612, 'name' => 'Caminos de Oriente'],
            ['commune_id' => 612, 'name' => 'Altos de la Pradera.'],

            ['commune_id' => 613, 'name' => 'La Isla'],
            ['commune_id' => 613, 'name' => 'Las Américas'],
            ['commune_id' => 613, 'name' => 'Alfonso López'],
            ['commune_id' => 613, 'name' => 'Las Acacias'],
            ['commune_id' => 613, 'name' => 'Nueva Granada'],
            ['commune_id' => 613, 'name' => 'Los Parques'],
            ['commune_id' => 613, 'name' => 'Guillermo Liévano'],
            ['commune_id' => 613, 'name' => 'La Florida'],
            ['commune_id' => 613, 'name' => 'Surorientales'],
            ['commune_id' => 613, 'name' => 'Los Alpes'],
            ['commune_id' => 613, 'name' => 'Rafael Azuero & Iachola'],
            ['commune_id' => 613, 'name' => 'La Paz'],
            ['commune_id' => 613, 'name' => 'Simón Bolívar'],
            ['commune_id' => 613, 'name' => 'Los Arrayanes'],
            ['commune_id' => 613, 'name' => 'Rafael Uribe Uribe'],
            ['commune_id' => 613, 'name' => 'Panorama'],
            ['commune_id' => 613, 'name' => 'San Carlos'],
            ['commune_id' => 613, 'name' => 'Villa Amarilla'],
            ['commune_id' => 613, 'name' => 'La Cristalina'],
            ['commune_id' => 613, 'name' => 'Bajo Pedregal'],
            ['commune_id' => 613, 'name' => 'El Peñón'],
            ['commune_id' => 613, 'name' => 'El Caracol'],
            ['commune_id' => 613, 'name' => 'El Porvenir'],
            ['commune_id' => 613, 'name' => 'a Esperanza'],
            ['commune_id' => 613, 'name' => 'Las Rocas'],
            ['commune_id' => 613, 'name' => 'Divino Niño'],
            ['commune_id' => 613, 'name' => 'Siete de Agosto'],
            ['commune_id' => 613, 'name' => 'Peñón Redondo'],
            ['commune_id' => 613, 'name' => 'Bajo Américas'],
            ['commune_id' => 613, 'name' => 'El Dorado'],
            ['commune_id' => 613, 'name' => 'La Cabuya'],
            ['commune_id' => 613, 'name' => 'Buenos Aires'],
            ['commune_id' => 613, 'name' => 'La Chamiza'],
            ['commune_id' => 613, 'name' => 'La Provincia.'],

            ['commune_id' => 614, 'name' => 'Trínidad'],
            ['commune_id' => 614, 'name' => 'Alberto Galindo'],
            ['commune_id' => 614, 'name' => 'José María Carbonell'],
            ['commune_id' => 614, 'name' => 'Luis Ignacio Andrade'],
            ['commune_id' => 614, 'name' => 'Eduardo Santos'],
            ['commune_id' => 614, 'name' => 'Darío Echandía'],
            ['commune_id' => 614, 'name' => 'Villa Magdalena'],
            ['commune_id' => 614, 'name' => 'La Riviera'],
            ['commune_id' => 614, 'name' => 'Luis Eduardo Vanegas'],
            ['commune_id' => 614, 'name' => 'Luis Carlos Galán'],
            ['commune_id' => 614, 'name' => 'Santa Rosa'],
            ['commune_id' => 614, 'name' => 'Carbonell 11'],
            ['commune_id' => 614, 'name' => 'Los Libertadores'],
            ['commune_id' => 614, 'name' => 'Minuto de Dios VI etapa'],
            ['commune_id' => 614, 'name' => 'Vicente Araújo'],
            ['commune_id' => 614, 'name' => 'Villa Nazaret'],
            ['commune_id' => 614, 'name' => 'El Progreso'],
            ['commune_id' => 614, 'name' => 'Virgilio Barco'],
            ['commune_id' => 614, 'name' => 'Villa Marcela'],
            ['commune_id' => 614, 'name' => 'Villa Esmeralda'],
            ['commune_id' => 614, 'name' => 'Calamari. Villa Colombia'],
            ['commune_id' => 614, 'name' => 'Alvaro Leyva Liévano'],
            ['commune_id' => 614, 'name' => 'Sector Galindo.'],

            ['commune_id' => 615, 'name' => 'La Rioja'],
            ['commune_id' => 615, 'name' => 'Once de Noviembre'],
            ['commune_id' => 615, 'name' => 'Misael Pastrana Borrero'],
            ['commune_id' => 615, 'name' => 'Los Comuneros'],
            ['commune_id' => 615, 'name' => 'Triunfo'],
            ['commune_id' => 615, 'name' => 'Las Camelias'],
            ['commune_id' => 615, 'name' => 'Palmas I  II Y III'],
            ['commune_id' => 615, 'name' => ' El Pedregal'],
            ['commune_id' => 615, 'name' => 'Santander'],
            ['commune_id' => 615, 'name' => 'Enrique Olaya Herrera'],
            ['commune_id' => 615, 'name' => 'Alberto Yepes'],
            ['commune_id' => 615, 'name' => 'Katakandrú'],
            ['commune_id' => 615, 'name' => 'Sector Barreiro'],
            ['commune_id' => 615, 'name' => 'Nuevo Horizonte'],
            ['commune_id' => 615, 'name' => 'Pablo Sexto'],
            ['commune_id' => 615, 'name' => 'Victor Félix Díaz'],
            ['commune_id' => 615, 'name' => 'Villa Nadia'],
            ['commune_id' => 615, 'name' => 'San Bernardo del Viento'],
            ['commune_id' => 615, 'name' => 'Oro Negro'],
            ['commune_id' => 615, 'name' => 'La "Víctoría'],
            ['commune_id' => 615, 'name' => 'Palmitas II'],
            ['commune_id' => 615, 'name' => 'La Pradera'],
            ['commune_id' => 615, 'name' => 'Granja San Bernardo'],
            ['commune_id' => 615, 'name' => 'Villa Aranzazu'],
            ['commune_id' => 615, 'name' => 'Folicarpo'],
            ['commune_id' => 615, 'name' => 'Calle Real'],
            ['commune_id' => 615, 'name' => 'El Paraíso'],
            ['commune_id' => 615, 'name' => 'Los Machines'],
            ['commune_id' => 615, 'name' => 'Los Rosales'],
            ['commune_id' => 615, 'name' => 'Los Colores'],
            ['commune_id' => 615, 'name' => 'El Oasis'],
            ['commune_id' => 615, 'name' => 'Antonio Nariño'],
            ['commune_id' => 615, 'name' => 'La Pradera'],

            ['commune_id' => 616, 'name' => 'San Francisco'],
            ['commune_id' => 616, 'name' => 'Peñas Blancas'],
            ['commune_id' => 616, 'name' => 'San Andrés'],
            ['commune_id' => 616, 'name' => 'San Jorge'],
            ['commune_id' => 616, 'name' => 'Guacirco'],
            ['commune_id' => 616, 'name' => 'La Jagua'],
            ['commune_id' => 616, 'name' => 'La Mata'],
            ['commune_id' => 616, 'name' => 'Fortalecillas'],
            ['commune_id' => 616, 'name' => 'El Venado'],
            ['commune_id' => 616, 'name' => 'La Mojarra'],
            ['commune_id' => 616, 'name' => 'El Espinal.'],

            ['commune_id' => 617, 'name' => 'El Centro'],
            ['commune_id' => 617, 'name' => 'Barro Negro'],
            ['commune_id' => 617, 'name' => 'Santa Bárbara'],
            ['commune_id' => 617, 'name' => 'San Bartolo'],
            ['commune_id' => 617, 'name' => 'Travesía'],
            ['commune_id' => 617, 'name' => 'El Chapuro'],
            ['commune_id' => 617, 'name' => 'El Triunfo.'],

            ['commune_id' => 618, 'name' => 'Santa Lucía'],
            ['commune_id' => 618, 'name' => 'Canoas'],
            ['commune_id' => 618, 'name' => 'Ceibas Adentro'],
            ['commune_id' => 618, 'name' => 'Motilón'],
            ['commune_id' => 618, 'name' => 'Alto Motilón'],
            ['commune_id' => 618, 'name' => 'Santa Librada'],
            ['commune_id' => 618, 'name' => 'Los Alpes'],
            ['commune_id' => 618, 'name' => 'El Roblal'],
            ['commune_id' => 618, 'name' => 'Las Pavás'],
            ['commune_id' => 618, 'name' => 'San José'],
            ['commune_id' => 618, 'name' => 'La Espiga'],
            ['commune_id' => 618, 'name' => 'San Antonio de Anaconía'],
            ['commune_id' => 618, 'name' => 'Palacio'],
            ['commune_id' => 618, 'name' => 'EI Tabor'],
            ['commune_id' => 618, 'name' => 'El Cedral'],
            ['commune_id' => 618, 'name' => 'Yucales'],
            ['commune_id' => 618, 'name' => 'Las Nubes'],
            ['commune_id' => 618, 'name' => 'Santa Iíelena'],
            ['commune_id' => 618, 'name' => 'La Plata'],
            ['commune_id' => 618, 'name' => 'Tuquila'],
            ['commune_id' => 618, 'name' => 'el Vergel'],
            ['commune_id' => 618, 'name' => 'Los Cauchos'],
            ['commune_id' => 618, 'name' => 'Platanillal'],
            ['commune_id' => 618, 'name' => 'Piedra Marcada'],
            ['commune_id' => 618, 'name' => 'Ahuyamales'],
            ['commune_id' => 618, 'name' => 'flora Gaita.'],

            ['commune_id' => 619, 'name' => 'La Julia'],
            ['commune_id' => 619, 'name' => 'Los Alpes'],
            ['commune_id' => 619, 'name' => 'Alto Cocal'],
            ['commune_id' => 619, 'name' => 'Cocal'],
            ['commune_id' => 619, 'name' => 'El Centro'],
            ['commune_id' => 619, 'name' => 'Quebradón'],
            ['commune_id' => 619, 'name' => 'Centro Avila'],
            ['commune_id' => 619, 'name' => 'La Libertad'],
            ['commune_id' => 619, 'name' => 'El Piñuelo'],
            ['commune_id' => 619, 'name' => 'Corozal'],
            ['commune_id' => 619, 'name' => 'El Palmar'],
            ['commune_id' => 619, 'name' => 'Aipecito'],
            ['commune_id' => 619, 'name' => 'La Unión'],
            ['commune_id' => 619, 'name' => 'La Pradera'],
            ['commune_id' => 619, 'name' => 'El Triunfo'],
            ['commune_id' => 619, 'name' => 'La florida'],
            ['commune_id' => 619, 'name' => 'Órganos'],
            ['commune_id' => 619, 'name' => 'Chapinero'],
            ['commune_id' => 619, 'name' => 'La Cabaña'],
            ['commune_id' => 619, 'name' => 'La Lindosa'],
            ['commune_id' => 619, 'name' => 'Diamante'],
            ['commune_id' => 619, 'name' => 'Altamíra'],
            ['commune_id' => 619, 'name' => 'Líbano'],
            ['commune_id' => 619, 'name' => 'Las Juntas'],
            ['commune_id' => 619, 'name' => 'Horizonte'],
            ['commune_id' => 619, 'name' => 'El Jardín'],
            ['commune_id' => 619, 'name' => 'Omega'],
            ['commune_id' => 620, 'name' => 'Otro'],

            ['commune_id' => 621, 'name' => 'Otro'],
            ['commune_id' => 622, 'name' => 'Otro'],
            ['commune_id' => 623, 'name' => 'Otro'],
            ['commune_id' => 624, 'name' => 'Otro'],
            ['commune_id' => 625, 'name' => 'Otro'],
            ['commune_id' => 626, 'name' => 'Otro'],
            ['commune_id' => 627, 'name' => 'Otro'],
            ['commune_id' => 628, 'name' => 'Otro'],
            ['commune_id' => 629, 'name' => 'Otro'],
            ['commune_id' => 630, 'name' => 'Otro'],
            ['commune_id' => 631, 'name' => 'Otro'],
            ['commune_id' => 632, 'name' => 'Otro'],
            ['commune_id' => 633, 'name' => 'Otro'],
            ['commune_id' => 634, 'name' => 'Otro'],
            ['commune_id' => 635, 'name' => 'Otro'],
            ['commune_id' => 636, 'name' => 'Otro'],
            ['commune_id' => 637, 'name' => 'Otro'],
            ['commune_id' => 638, 'name' => 'Otro'],
            ['commune_id' => 639, 'name' => 'Otro'],
            ['commune_id' => 640, 'name' => 'Otro'],
            ['commune_id' => 641, 'name' => 'Otro'],
            ['commune_id' => 642, 'name' => 'Otro'],
            ['commune_id' => 643, 'name' => 'Otro'],
            ['commune_id' => 644, 'name' => 'Otro'],
            ['commune_id' => 645, 'name' => 'Otro'],
            ['commune_id' => 646, 'name' => 'Otro'],
            ['commune_id' => 647, 'name' => 'Otro'],
            ['commune_id' => 648, 'name' => 'Otro'],
            ['commune_id' => 649, 'name' => 'Otro'],
            ['commune_id' => 650, 'name' => 'Otro'],
            ['commune_id' => 651, 'name' => 'Otro'],
            ['commune_id' => 652, 'name' => 'Otro'],
            ['commune_id' => 653, 'name' => 'Otro'],
            ['commune_id' => 654, 'name' => 'Otro'],
            ['commune_id' => 655, 'name' => 'Otro'],
            ['commune_id' => 656, 'name' => 'Otro'],
            ['commune_id' => 657, 'name' => 'Otro'],
            ['commune_id' => 658, 'name' => 'Otro'],
            ['commune_id' => 659, 'name' => 'Otro'],
            ['commune_id' => 660, 'name' => 'Otro'],
            ['commune_id' => 661, 'name' => 'Otro'],
            ['commune_id' => 662, 'name' => 'Otro'],
            ['commune_id' => 663, 'name' => 'Otro'],
            ['commune_id' => 664, 'name' => 'Otro'],
            ['commune_id' => 665, 'name' => 'Otro'],
            ['commune_id' => 666, 'name' => 'Otro'],
            ['commune_id' => 667, 'name' => 'Otro'],
            ['commune_id' => 668, 'name' => 'Otro'],
            ['commune_id' => 669, 'name' => 'Otro'],
            ['commune_id' => 670, 'name' => 'Otro'],
            ['commune_id' => 671, 'name' => 'Otro'],
            ['commune_id' => 672, 'name' => 'Otro'],
            ['commune_id' => 673, 'name' => 'Otro'],
            ['commune_id' => 674, 'name' => 'Otro'],
            ['commune_id' => 675, 'name' => 'Otro'],
            ['commune_id' => 676, 'name' => 'Otro'],
            ['commune_id' => 677, 'name' => 'Otro'],
            ['commune_id' => 678, 'name' => 'Otro'],
            ['commune_id' => 679, 'name' => 'Otro'],
            ['commune_id' => 680, 'name' => 'Otro'],
            ['commune_id' => 681, 'name' => 'Otro'],
            ['commune_id' => 682, 'name' => 'Otro'],
            ['commune_id' => 683, 'name' => 'Otro'],
            ['commune_id' => 684, 'name' => 'Otro'],
            ['commune_id' => 685, 'name' => 'Otro'],
            ['commune_id' => 686, 'name' => 'Otro'],
            ['commune_id' => 687, 'name' => 'Otro'],
            ['commune_id' => 688, 'name' => 'Otro'],
            ['commune_id' => 689, 'name' => 'Otro'],
            ['commune_id' => 690, 'name' => 'Otro'],
            ['commune_id' => 691, 'name' => 'Otro'],
            ['commune_id' => 692, 'name' => 'Otro'],
            ['commune_id' => 693, 'name' => 'Otro'],
            ['commune_id' => 694, 'name' => 'Otro'],
            ['commune_id' => 695, 'name' => 'Otro'],
            ['commune_id' => 696, 'name' => 'Otro'],
            ['commune_id' => 697, 'name' => 'Otro'],
            ['commune_id' => 698, 'name' => 'Otro'],
            ['commune_id' => 699, 'name' => 'Otro'],
            ['commune_id' => 700, 'name' => 'Otro'],
            ['commune_id' => 701, 'name' => 'Otro'],
            ['commune_id' => 702, 'name' => 'Otro'],
            ['commune_id' => 703, 'name' => 'Otro'],
            ['commune_id' => 704, 'name' => 'Otro'],
            ['commune_id' => 705, 'name' => 'Otro'],
            ['commune_id' => 706, 'name' => 'Otro'],
            ['commune_id' => 707, 'name' => 'Otro'],
            ['commune_id' => 708, 'name' => 'Otro'],
            ['commune_id' => 709, 'name' => 'Otro'],
            ['commune_id' => 710, 'name' => 'Otro'],
            ['commune_id' => 711, 'name' => 'Otro'],
            ['commune_id' => 712, 'name' => 'Otro'],
            ['commune_id' => 713, 'name' => 'Otro'],
            ['commune_id' => 714, 'name' => 'Otro'],
            ['commune_id' => 715, 'name' => 'Otro'],
            ['commune_id' => 716, 'name' => 'Otro'],
            ['commune_id' => 717, 'name' => 'Otro'],
            ['commune_id' => 718, 'name' => 'Otro'],
            ['commune_id' => 719, 'name' => 'Otro'],
            ['commune_id' => 720, 'name' => 'Otro'],
            ['commune_id' => 721, 'name' => 'Otro'],
            ['commune_id' => 722, 'name' => 'Otro'],
            ['commune_id' => 723, 'name' => 'Otro'],
            ['commune_id' => 724, 'name' => 'Otro'],
            ['commune_id' => 725, 'name' => 'Otro'],
            ['commune_id' => 726, 'name' => 'Otro'],
            ['commune_id' => 727, 'name' => 'Otro'],
            ['commune_id' => 728, 'name' => 'Otro'],
            ['commune_id' => 729, 'name' => 'Otro'],
            ['commune_id' => 730, 'name' => 'Otro'],
            ['commune_id' => 731, 'name' => 'Otro'],
            ['commune_id' => 732, 'name' => 'Otro'],
            ['commune_id' => 733, 'name' => 'Otro'],
            ['commune_id' => 734, 'name' => 'Otro'],
            ['commune_id' => 735, 'name' => 'Otro'],
            ['commune_id' => 736, 'name' => 'Otro'],
            ['commune_id' => 737, 'name' => 'Otro'],
            ['commune_id' => 738, 'name' => 'Otro'],
            ['commune_id' => 739, 'name' => 'Otro'],
            ['commune_id' => 740, 'name' => 'Otro'],
            ['commune_id' => 741, 'name' => 'Otro'],
            ['commune_id' => 742, 'name' => 'Otro'],
            ['commune_id' => 743, 'name' => 'Otro'],
            ['commune_id' => 744, 'name' => 'Otro'],
            ['commune_id' => 745, 'name' => 'Otro'],
            ['commune_id' => 746, 'name' => 'Otro'],
            ['commune_id' => 747, 'name' => 'Otro'],
            ['commune_id' => 748, 'name' => 'Otro'],
            ['commune_id' => 749, 'name' => 'Otro'],
            ['commune_id' => 750, 'name' => 'Otro'],
            ['commune_id' => 751, 'name' => 'Otro'],
            ['commune_id' => 752, 'name' => 'Otro'],
            ['commune_id' => 753, 'name' => 'Otro'],
            ['commune_id' => 754, 'name' => 'Otro'],
            ['commune_id' => 755, 'name' => 'Otro'],
            ['commune_id' => 756, 'name' => 'Otro'],
            ['commune_id' => 757, 'name' => 'Otro'],
            ['commune_id' => 758, 'name' => 'Otro'],
            ['commune_id' => 759, 'name' => 'Otro'],
            ['commune_id' => 760, 'name' => 'Otro'],
            ['commune_id' => 761, 'name' => 'Otro'],
            ['commune_id' => 762, 'name' => 'Otro'],
            ['commune_id' => 763, 'name' => 'Otro'],
            ['commune_id' => 764, 'name' => 'Otro'],
            ['commune_id' => 765, 'name' => 'Otro'],
            ['commune_id' => 766, 'name' => 'Otro'],
            ['commune_id' => 767, 'name' => 'Otro'],
            ['commune_id' => 768, 'name' => 'Otro'],
            ['commune_id' => 769, 'name' => 'Otro'],
            ['commune_id' => 770, 'name' => 'Otro'],
            ['commune_id' => 771, 'name' => 'Otro'],
            ['commune_id' => 772, 'name' => 'Otro'],
            ['commune_id' => 773, 'name' => 'Otro'],
            ['commune_id' => 774, 'name' => 'Otro'],
            ['commune_id' => 775, 'name' => 'Otro'],
            ['commune_id' => 776, 'name' => 'Otro'],
            ['commune_id' => 777, 'name' => 'Otro'],
            ['commune_id' => 778, 'name' => 'Otro'],
            ['commune_id' => 779, 'name' => 'Otro'],
            ['commune_id' => 780, 'name' => 'Otro'],
            ['commune_id' => 781, 'name' => 'Otro'],
            ['commune_id' => 782, 'name' => 'Otro'],
            ['commune_id' => 783, 'name' => 'Otro'],
            ['commune_id' => 784, 'name' => 'Otro'],
            ['commune_id' => 785, 'name' => 'Otro'],
            ['commune_id' => 786, 'name' => 'Otro'],
            ['commune_id' => 787, 'name' => 'Otro'],
            ['commune_id' => 788, 'name' => 'Otro'],
            ['commune_id' => 789, 'name' => 'Otro'],
            ['commune_id' => 790, 'name' => 'Otro'],
            ['commune_id' => 791, 'name' => 'Otro'],
            ['commune_id' => 792, 'name' => 'Otro'],
            ['commune_id' => 793, 'name' => 'Otro'],
            ['commune_id' => 794, 'name' => 'Otro'],
            ['commune_id' => 795, 'name' => 'Otro'],
            ['commune_id' => 796, 'name' => 'Otro'],
            ['commune_id' => 797, 'name' => 'Otro'],
            ['commune_id' => 798, 'name' => 'Otro'],
            ['commune_id' => 799, 'name' => 'Otro'],
            ['commune_id' => 800, 'name' => 'Otro'],
            ['commune_id' => 801, 'name' => 'Otro'],
            ['commune_id' => 802, 'name' => 'Otro'],
            ['commune_id' => 803, 'name' => 'Otro'],
            ['commune_id' => 804, 'name' => 'Otro'],
            ['commune_id' => 805, 'name' => 'Otro'],
            ['commune_id' => 806, 'name' => 'Otro'],
            ['commune_id' => 807, 'name' => 'Otro'],
            ['commune_id' => 808, 'name' => 'Otro'],
            ['commune_id' => 809, 'name' => 'Otro'],
            ['commune_id' => 810, 'name' => 'Otro'],
            ['commune_id' => 811, 'name' => 'Otro'],
            ['commune_id' => 812, 'name' => 'Otro'],
            ['commune_id' => 813, 'name' => 'Otro'],
            ['commune_id' => 814, 'name' => 'Otro'],
            ['commune_id' => 815, 'name' => 'Otro'],
            ['commune_id' => 816, 'name' => 'Otro'],
            ['commune_id' => 817, 'name' => 'Otro'],
            ['commune_id' => 818, 'name' => 'Otro'],
            ['commune_id' => 819, 'name' => 'Otro'],
            ['commune_id' => 820, 'name' => 'Otro'],
            ['commune_id' => 821, 'name' => 'Otro'],
            ['commune_id' => 822, 'name' => 'Otro'],
            ['commune_id' => 823, 'name' => 'Otro'],
            ['commune_id' => 824, 'name' => 'Otro'],
            ['commune_id' => 825, 'name' => 'Otro'],
            ['commune_id' => 826, 'name' => 'Otro'],
            ['commune_id' => 827, 'name' => 'Otro'],
            ['commune_id' => 828, 'name' => 'Otro'],
            ['commune_id' => 829, 'name' => 'Otro'],
            ['commune_id' => 830, 'name' => 'Otro'],
            ['commune_id' => 831, 'name' => 'Otro'],
            ['commune_id' => 832, 'name' => 'Otro'],
            ['commune_id' => 833, 'name' => 'Otro'],
            ['commune_id' => 834, 'name' => 'Otro'],
            ['commune_id' => 835, 'name' => 'Otro'],
            ['commune_id' => 836, 'name' => 'Otro'],
            ['commune_id' => 837, 'name' => 'Otro'],
            ['commune_id' => 838, 'name' => 'Otro'],
            ['commune_id' => 839, 'name' => 'Otro'],
            ['commune_id' => 840, 'name' => 'Otro'],
            ['commune_id' => 841, 'name' => 'Otro'],
            ['commune_id' => 842, 'name' => 'Otro'],
            ['commune_id' => 843, 'name' => 'Otro'],
            ['commune_id' => 844, 'name' => 'Otro'],
            ['commune_id' => 845, 'name' => 'Otro'],
            ['commune_id' => 846, 'name' => 'Otro'],
            ['commune_id' => 847, 'name' => 'Otro'],
            ['commune_id' => 848, 'name' => 'Otro'],
            ['commune_id' => 849, 'name' => 'Otro'],
            ['commune_id' => 850, 'name' => 'Otro'],
            ['commune_id' => 851, 'name' => 'Otro'],
            ['commune_id' => 852, 'name' => 'Otro'],
            ['commune_id' => 853, 'name' => 'Otro'],
            ['commune_id' => 854, 'name' => 'Otro'],
            ['commune_id' => 855, 'name' => 'Otro'],
            ['commune_id' => 856, 'name' => 'Otro'],
            ['commune_id' => 857, 'name' => 'Otro'],
            ['commune_id' => 858, 'name' => 'Otro'],
            ['commune_id' => 859, 'name' => 'Otro'],
            ['commune_id' => 860, 'name' => 'Otro'],
            ['commune_id' => 861, 'name' => 'Otro'],
            ['commune_id' => 862, 'name' => 'Otro'],
            ['commune_id' => 863, 'name' => 'Otro'],
            ['commune_id' => 864, 'name' => 'Otro'],
            ['commune_id' => 865, 'name' => 'Otro'],
            ['commune_id' => 866, 'name' => 'Otro'],
            ['commune_id' => 867, 'name' => 'Otro'],
            ['commune_id' => 868, 'name' => 'Otro'],
            ['commune_id' => 869, 'name' => 'Otro'],
            ['commune_id' => 870, 'name' => 'Otro'],
            ['commune_id' => 871, 'name' => 'Otro'],
            ['commune_id' => 872, 'name' => 'Otro'],
            ['commune_id' => 873, 'name' => 'Otro'],
            ['commune_id' => 874, 'name' => 'Otro'],
            ['commune_id' => 875, 'name' => 'Otro'],
            ['commune_id' => 876, 'name' => 'Otro'],
            ['commune_id' => 877, 'name' => 'Otro'],
            ['commune_id' => 878, 'name' => 'Otro'],
            ['commune_id' => 879, 'name' => 'Otro'],
            ['commune_id' => 880, 'name' => 'Otro'],
            ['commune_id' => 881, 'name' => 'Otro'],
            ['commune_id' => 882, 'name' => 'Otro'],
            ['commune_id' => 883, 'name' => 'Otro'],
            ['commune_id' => 884, 'name' => 'Otro'],
            ['commune_id' => 885, 'name' => 'Otro'],
            ['commune_id' => 886, 'name' => 'Otro'],
            ['commune_id' => 887, 'name' => 'Otro'],
            ['commune_id' => 888, 'name' => 'Otro'],
            ['commune_id' => 889, 'name' => 'Otro'],
            ['commune_id' => 890, 'name' => 'Otro'],
            ['commune_id' => 891, 'name' => 'Otro'],
            ['commune_id' => 892, 'name' => 'Otro'],
            ['commune_id' => 893, 'name' => 'Otro'],
            ['commune_id' => 894, 'name' => 'Otro'],
            ['commune_id' => 895, 'name' => 'Otro'],
            ['commune_id' => 896, 'name' => 'Otro'],
            ['commune_id' => 897, 'name' => 'Otro'],
            ['commune_id' => 898, 'name' => 'Otro'],
            ['commune_id' => 899, 'name' => 'Otro'],
            ['commune_id' => 900, 'name' => 'Otro'],
            ['commune_id' => 901, 'name' => 'Otro'],
            ['commune_id' => 902, 'name' => 'Otro'],
            ['commune_id' => 903, 'name' => 'Otro'],
            ['commune_id' => 904, 'name' => 'Otro'],
            ['commune_id' => 905, 'name' => 'Otro'],
            ['commune_id' => 906, 'name' => 'Otro'],
            ['commune_id' => 907, 'name' => 'Otro'],
            ['commune_id' => 908, 'name' => 'Otro'],
            ['commune_id' => 909, 'name' => 'Otro'],
            ['commune_id' => 910, 'name' => 'Otro'],
            ['commune_id' => 911, 'name' => 'Otro'],
            ['commune_id' => 912, 'name' => 'Otro'],
            ['commune_id' => 913, 'name' => 'Otro'],
            ['commune_id' => 914, 'name' => 'Otro'],
            ['commune_id' => 915, 'name' => 'Otro'],
            ['commune_id' => 916, 'name' => 'Otro'],
            ['commune_id' => 917, 'name' => 'Otro'],
            ['commune_id' => 918, 'name' => 'Otro'],
            ['commune_id' => 919, 'name' => 'Otro'],
            ['commune_id' => 920, 'name' => 'Otro'],
            ['commune_id' => 921, 'name' => 'Otro'],
            ['commune_id' => 922, 'name' => 'Otro'],
            ['commune_id' => 923, 'name' => 'Otro'],
            ['commune_id' => 924, 'name' => 'Otro'],
            ['commune_id' => 925, 'name' => 'Otro'],
            ['commune_id' => 926, 'name' => 'Otro'],
            ['commune_id' => 927, 'name' => 'Otro'],
            ['commune_id' => 928, 'name' => 'Otro'],
            ['commune_id' => 929, 'name' => 'Otro'],
            ['commune_id' => 930, 'name' => 'Otro'],
            ['commune_id' => 931, 'name' => 'Otro'],
            ['commune_id' => 932, 'name' => 'Otro'],
            ['commune_id' => 933, 'name' => 'Otro'],
            ['commune_id' => 934, 'name' => 'Otro'],
            ['commune_id' => 935, 'name' => 'Otro'],
            ['commune_id' => 936, 'name' => 'Otro'],
            ['commune_id' => 937, 'name' => 'Otro'],
            ['commune_id' => 938, 'name' => 'Otro'],
            ['commune_id' => 939, 'name' => 'Otro'],
            ['commune_id' => 940, 'name' => 'Otro'],
            ['commune_id' => 941, 'name' => 'Otro'],
            ['commune_id' => 942, 'name' => 'Otro'],
            ['commune_id' => 943, 'name' => 'Otro'],
            ['commune_id' => 944, 'name' => 'Otro'],
            ['commune_id' => 945, 'name' => 'Otro'],
            ['commune_id' => 946, 'name' => 'Otro'],
            ['commune_id' => 947, 'name' => 'Otro'],
            ['commune_id' => 948, 'name' => 'Otro'],
            ['commune_id' => 949, 'name' => 'Otro'],
            ['commune_id' => 950, 'name' => 'Otro'],
            ['commune_id' => 951, 'name' => 'Otro'],
            ['commune_id' => 952, 'name' => 'Otro'],
            ['commune_id' => 953, 'name' => 'Otro'],
            ['commune_id' => 954, 'name' => 'Otro'],
            ['commune_id' => 955, 'name' => 'Otro'],
            ['commune_id' => 956, 'name' => 'Otro'],
            ['commune_id' => 957, 'name' => 'Otro'],
            ['commune_id' => 958, 'name' => 'Otro'],
            ['commune_id' => 959, 'name' => 'Otro'],
            ['commune_id' => 960, 'name' => 'Otro'],
            ['commune_id' => 961, 'name' => 'Otro'],
            ['commune_id' => 962, 'name' => 'Otro'],
            ['commune_id' => 963, 'name' => 'Otro'],
            ['commune_id' => 964, 'name' => 'Otro'],
            ['commune_id' => 965, 'name' => 'Otro'],
            ['commune_id' => 966, 'name' => 'Otro'],
            ['commune_id' => 967, 'name' => 'Otro'],
            ['commune_id' => 968, 'name' => 'Otro'],
            ['commune_id' => 969, 'name' => 'Otro'],
            ['commune_id' => 970, 'name' => 'Otro'],
            ['commune_id' => 971, 'name' => 'Otro'],
            ['commune_id' => 972, 'name' => 'Otro'],
            ['commune_id' => 973, 'name' => 'Otro'],
            ['commune_id' => 974, 'name' => 'Otro'],
            ['commune_id' => 975, 'name' => 'Otro'],
            ['commune_id' => 976, 'name' => 'Otro'],
            ['commune_id' => 977, 'name' => 'Otro'],
            ['commune_id' => 978, 'name' => 'Otro'],
            ['commune_id' => 979, 'name' => 'Otro'],
            ['commune_id' => 980, 'name' => 'Otro'],
            ['commune_id' => 981, 'name' => 'Otro'],
            ['commune_id' => 982, 'name' => 'Otro'],
            ['commune_id' => 983, 'name' => 'Otro'],
            ['commune_id' => 984, 'name' => 'Otro'],
            ['commune_id' => 985, 'name' => 'Otro'],
            ['commune_id' => 986, 'name' => 'Otro'],
            ['commune_id' => 987, 'name' => 'Otro'],
            ['commune_id' => 988, 'name' => 'Otro'],
            ['commune_id' => 989, 'name' => 'Otro'],
            ['commune_id' => 990, 'name' => 'Otro'],
            ['commune_id' => 991, 'name' => 'Otro'],
            ['commune_id' => 992, 'name' => 'Otro'],
            ['commune_id' => 993, 'name' => 'Otro'],
            ['commune_id' => 994, 'name' => 'Otro'],
            ['commune_id' => 995, 'name' => 'Otro'],
            ['commune_id' => 996, 'name' => 'Otro'],
            ['commune_id' => 997, 'name' => 'Otro'],
            ['commune_id' => 998, 'name' => 'Otro'],
            ['commune_id' => 999, 'name' => 'Otro'],
            ['commune_id' => 1000, 'name' => 'Otro'],
            ['commune_id' => 1001, 'name' => 'Otro'],
            ['commune_id' => 1002, 'name' => 'Otro'],
            ['commune_id' => 1003, 'name' => 'Otro'],
            ['commune_id' => 1004, 'name' => 'Otro'],
            ['commune_id' => 1005, 'name' => 'Otro'],
            ['commune_id' => 1006, 'name' => 'Otro'],
            ['commune_id' => 1007, 'name' => 'Otro'],
            ['commune_id' => 1008, 'name' => 'Otro'],
            ['commune_id' => 1009, 'name' => 'Otro'],
            ['commune_id' => 1010, 'name' => 'Otro'],
            ['commune_id' => 1011, 'name' => 'Otro'],
            ['commune_id' => 1012, 'name' => 'Otro'],
            ['commune_id' => 1013, 'name' => 'Otro'],
            ['commune_id' => 1014, 'name' => 'Otro'],
            ['commune_id' => 1015, 'name' => 'Otro'],
            ['commune_id' => 1016, 'name' => 'Otro'],
            ['commune_id' => 1017, 'name' => 'Otro'],
            ['commune_id' => 1018, 'name' => 'Otro'],
            ['commune_id' => 1019, 'name' => 'Otro'],
            ['commune_id' => 1020, 'name' => 'Otro'],
            ['commune_id' => 1021, 'name' => 'Otro'],
            ['commune_id' => 1022, 'name' => 'Otro'],
            ['commune_id' => 1023, 'name' => 'Otro'],
            ['commune_id' => 1024, 'name' => 'Otro'],
            ['commune_id' => 1025, 'name' => 'Otro'],
            ['commune_id' => 1026, 'name' => 'Otro'],
            ['commune_id' => 1027, 'name' => 'Otro'],
            ['commune_id' => 1028, 'name' => 'Otro'],
            ['commune_id' => 1029, 'name' => 'Otro'],
            ['commune_id' => 1030, 'name' => 'Otro'],
            ['commune_id' => 1031, 'name' => 'Otro'],
            ['commune_id' => 1032, 'name' => 'Otro'],
            ['commune_id' => 1033, 'name' => 'Otro'],
            ['commune_id' => 1034, 'name' => 'Otro'],
            ['commune_id' => 1035, 'name' => 'Otro'],
            ['commune_id' => 1036, 'name' => 'Otro'],
            ['commune_id' => 1037, 'name' => 'Otro'],
            ['commune_id' => 1038, 'name' => 'Otro'],
            ['commune_id' => 1039, 'name' => 'Otro'],
            ['commune_id' => 1040, 'name' => 'Otro'],
            ['commune_id' => 1041, 'name' => 'Otro'],
            ['commune_id' => 1042, 'name' => 'Otro'],

        );

        foreach ($neighborhoods as $n) {
            Neighborhood::updateOrCreate($n);
        }
    }
}
